name = "Arpan Garai"
license = "MIT"
licenselink = "https://github.com/schnerring/hugo-theme-gruvbox/blob/main/LICENSE"
description = "An Experimental Physicist's load full of bullshit.."
homepage = "https://github.com/schnerring/hugo-theme-gruvbox"
demosite = "https://hugo-theme-gruvbox.schnerring.net"
tags = [
  "blog",
  "dark mode",
  "minimal",
  "personal",
  "responsive"
]
features = ["dark mode"]

[author]
  name = "Arpan Garai"
  homepage = "https://schnerring.net"
